"""dobavili tablici Drons i Cameras

Revision ID: 72dd1d582849
Revises: 69d35f4a8993
Create Date: 2023-12-27 02:09:28.130446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dd1d582849'
down_revision = '69d35f4a8993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=12), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photo_cameras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_cameras',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=5, scale=12), nullable=True),
    sa.Column('photo', sa.BLOB(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cameras')
    # ### end Alembic commands ###
