"""empty message

Revision ID: 888b7aa88df5
Revises: 9326c49de6a1
Create Date: 2024-03-17 03:17:17.571147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888b7aa88df5'
down_revision = '9326c49de6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
