"""rabota nad users drons camera

Revision ID: 9326c49de6a1
Revises: d57f0fcc4687
Create Date: 2024-03-16 23:16:15.106416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9326c49de6a1'
down_revision = 'd57f0fcc4687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drons', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drons', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
